// utils/breadcrumbTitles.ts
export const breadcrumbTitles: Record<string, string> = {
  dashboard: 'Inicio',
  readings: 'Lecturas',
  billing: 'Facturación',
  subscribers: 'Suscriptores',
  tenants: 'Inquilinos (usuarios)',
  properties: 'Predios',
  meters: 'Medidores',
  routes: 'Rutas de Lectura',
  rates: 'Tarifas',
  'consumption-ranges': 'Rangos de Consumo',
  subsidies: 'Subsidios',
  concepts: 'Conceptos de Factura',
  financing: 'Financiación',
  agreements: 'Convenios',
  users: 'Usuarios Internos',
  employees: 'Empleados',
  services: 'Servicios',
  'cycles-routes': 'Ciclos y rutas',
  reports: 'Reportes',
  editar: 'Editar',
  crear: 'Crear',
  profile: 'Mi perfil',
}
